apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: robbot
build:
  artifacts:
  - image: us.gcr.io/robbot-discord/robbot
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
profiles:
- name: kaniko
  build:
    artifacts:
    - image: us.gcr.io/robbot-discord/robbot
      kaniko:
        reproducible: true
        image: gcr.io/kaniko-project/executor:debug
- name: googleCloudBuild
  build:
    googleCloudBuild:
      projectId: robbot-discord
