apiVersion: v1
kind: Pod
metadata:
  name: skaffold
spec:
  containers:
    - name: skaffold
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
      image: gcr.io/k8s-skaffold/skaffold:latest
      command:
        - cat
      tty: true
      resources:
          limits:
            cpu: "1"
            memory: "1Gi" 
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret/
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
